# _config.yml
title: Zerojudge 解題紀錄
description: SUNGOD 的 程式解題筆記
baseurl: ""
url: "https://SUNGOD3.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page:num/"

collections:
  solutions:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "SUNGOD"